apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: crpi-7v8gwt2o8un00872.cn-beijing.personal.cr.aliyuncs.com/myrepo_ok/service_a:v1  # 镜像地址
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: NodePort
  selector:
    app: service-a
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

