definitions:
  dto.Response:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 数据，成功时返回数据，失败时返回错误信息
      message:
        description: 响应信息
        type: string
      status:
        description: success 或 error
        type: string
    type: object
  model.SetOrderReq:
    properties:
      id:
        type: integer
      name:
        type: string
      num:
        type: integer
      price:
        type: integer
    type: object
info:
  contact: { }
paths:
  /order:
    post:
      consumes:
      - application/json
      description: 通过此接口提交一个订单，包含商品数量和价格
      parameters:
      - description: 订单请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.SetOrderReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/dto.Response'
      tags:
      - Order
swagger: "2.0"
