apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea
  labels:
    app: servicea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
      - name: servicea
        image: servicea:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: servicea
spec:
  selector:
    app: servicea
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 