apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: crpi-7v8gwt2o8un00872.cn-beijing.personal.cr.aliyuncs.com/myrepo_ok/service_b:v1  # 镜像地址
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  type: NodePort
  selector:
    app: service-b
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080

